### ISSUE TITLE
Unable to download Upscaler Bases.zip (404) and Data_ccfsvsse001-backpacks.esl (No URL)

### ISSUE THREAD

**Issue by tongko** [The-Animonculory/AVO-NG#4] opened 2023-05-03 02:28 UTC
[Wabbajack.current.log](https://github.com/The-Animonculory/AVO-NG/files/11378504/Wabbajack.current.log)

If you've crashed, upload your crash log from `C:\Users\UserName\Documents\My Games\Skyrim Special Edition`. Reports of crashes that do not include a crash log will be **ignored and closed.**

[C:\Games\Wabbajack\3.0.6.2\downloaded_mod_lists]

Installation failed due to  failed to download above mention 2 files.

**To Reproduce**
1. Install Wabbajack 3.0.6.2.
2. Download AVO-NG 4.1
3. Run

**Expected behaviour**
Source of mod should not be 404.

**Did you add any additional mods?**
No mod added.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment] 2023-05-03 06:47
Duplicate of issue 3.

**Closed** 2023-05-03 06:47 UTC
